### ISSUE TITLE
Problem with x_to_dict()

### ISSUE THREAD

**Issue by JoeSgambellone** [mattmccormick/statprocon#10]
Hello Matt,

I am unable to reproduce the SPC charts with the values and code supplied by the readme. I’m able to import everything and assign values (unpl, mr_cl, etc) so those work, but I’m having trouble with the line: 

`pd.DataFrame(xmr.x_to_dict(),` index=labels).astype(float).plot()

The error says: Length of values (4) does not match length or index (1)

![image](https://github.com/mattmccormick/statprocon/assets/164236278/6df5605e-e290-4adf-a8d2-9b55cad65d96)

Thank you.

**Comment by mattmccormick** [comment]
Hi Joe,

`labels` should be a list of strings.  Those will be displayed on the X Axis.  In the README file, `[...]` is used to indicate a list of whatever values make sense for your labels.  I can see how it can be confusing though.

I've updated the README file and hopefully it's clearer now https://github.com/mattmccormick/statprocon?tab=readme-ov-file#pandas

```python
labels = ['0', '1', '2', '3']
pd.DataFrame(xmr.x_to_dict(), index=labels).astype(float).plot()
```

**Comment by JoeSgambellone** [comment]
Looks good and works. Thanks!
